### PR TITLE
Maui countries branch

### PR DESCRIPTION
**Pull request by Roche-MauiJane**
Add and organize country folders for exercise 14 - 1c7ef660b2b042fa45e88363dffd8e17882a5294
Add a button and a search box - 76e4f5c8d042350bceddb10916f97e3e0911894f
Display 5 details - c96ed8c8d2ce8962d6b28030f3be16118621ce21
Add Api that will fetch countries - e83166731705d80f79aa55ef372c7af0fe6f02a9

### CODE REVIEW

**Review by KazelVillamarzo — CHANGES_REQUESTED** [review]
Your JS are not following some guidelines in lines 37, 45, 79 and more Separate every function block with a single space.
Refer to the below coding guideline. and Do not use arrow function as a method of an object.

https://docs.google.com/presentation/d/1iCoz17mBxZtIQ9PifAW0jjKsuv4xDTlx-TPQxdLySow/edit?fbclid=IwZXh0bgNhZW0CMTAAAR0Iybnk0psj0nA39x7qXgjTS5PyEXYJFPIM6Fzhl3vbv1SGw_Gp0pYV1xU_aem_AaPBrad1Cnuh4v8RKgeLRJV7Bch6KHCoISrQW57HR35WvCGUG1HQi7ZdjcyLQ48KKFRkn2x8-eL8GZTJLBlYmqFo#slide=id.g25d183194fb_0_0

**Review by KazelVillamarzo — CHANGES_REQUESTED** [review]
in your countries.html  roche_mauijane/html_files/countries.html it's not following the guideline 
refer to the link below 
IDs should be written in snake case. All lower case separated by underscore.

**Comment by Roche-MauiJane** [comment]
> in your countries.html roche_mauijane/html_files/countries.html it's not following the guideline The IDs should be written in snake case. All lower case separated by underscore. refer to the link below https://docs.google.com/presentation/d/1iCoz17mBxZtIQ9PifAW0jjKsuv4xDTlx-TPQxdLySow/edit?fbclid=IwZXh0bgNhZW0CMTAAAR0Iybnk0psj0nA39x7qXgjTS5PyEXYJFPIM6Fzhl3vbv1SGw_Gp0pYV1xU_aem_AaPBrad1Cnuh4v8RKgeLRJV7Bch6KHCoISrQW57HR35WvCGUG1HQi7ZdjcyLQ48KKFRkn2x8-eL8GZTJLBlYmqFo#slide=id.g24da8de92d7_0_5

change id's to snake case c2196b37a1450dedb0eb9f4190beac9bfc713474

**Review by KazelVillamarzo — APPROVED** [review]
I'll Approve this

**Comment by Roche-MauiJane** [comment]
> I'll Approve this



> I'll Approve this

Thankyou!

**Pull request merged**
